import './globals.css'
// import { Inter } from 'next/font/google'

import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'

// const inter = Inter({
//   weight: ['300', '400', '500', '600', '700'],
//   subsets: ['latin']
// })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='body-container'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
